// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuasarQuant.Repository.Signals;

#nullable disable

namespace QuasarQuant.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuasarQuant.Core.Models.TradeSignal", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<string>("featureSetName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("feature_set_name");

                    b.Property<DateTime>("generatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<string>("modelVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_version");

                    b.Property<Guid>("portfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_id");

                    b.Property<double>("positionSizePct")
                        .HasColumnType("double precision")
                        .HasColumnName("position_size_pct");

                    b.Property<string>("predictionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prediction_id");

                    b.Property<double>("recommendedPrice")
                        .HasColumnType("double precision")
                        .HasColumnName("recommended_price");

                    b.Property<double>("riskScore")
                        .HasColumnType("double precision")
                        .HasColumnName("risk_score");

                    b.Property<string>("signal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("signal");

                    b.Property<string>("source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("symbol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("symbol");

                    b.Property<DateTime>("targetTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("target_timestamp");

                    b.Property<string>("timeframe")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timeframe");

                    b.Property<Guid>("userId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("id")
                        .HasName("pk_trade_signals");

                    b.ToTable("trade_signals", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
